/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

/**
 *
 * @author Marc
 */
public class MainMenu extends javax.swing.JFrame
{

    /**
     * Creates new form MainMenu
     */
    public MainMenu()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabTitle = new javax.swing.JLabel();
        jButExit = new javax.swing.JButton();
        jButNewStudent = new javax.swing.JButton();
        jButShowStudents = new javax.swing.JButton();
        jButDeleteStudents = new javax.swing.JButton();
        jButSearchStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTitle.setText("Student Register");
        jLabTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButExit.setText("Exit");
        jButExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButExitActionPerformed(evt);
            }
        });

        jButNewStudent.setText("New student");
        jButNewStudent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButNewStudentActionPerformed(evt);
            }
        });

        jButShowStudents.setText("Show students");
        jButShowStudents.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButShowStudentsActionPerformed(evt);
            }
        });

        jButDeleteStudents.setText("Delete student");
        jButDeleteStudents.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButDeleteStudentsActionPerformed(evt);
            }
        });

        jButSearchStudent.setText("Search student by DNI");
        jButSearchStudent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButSearchStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButShowStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButDeleteStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButExit, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(295, 295, 295))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButNewStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButShowStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButDeleteStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButExit, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButExitActionPerformed
    {//GEN-HEADEREND:event_jButExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButExitActionPerformed

    private void jButNewStudentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButNewStudentActionPerformed
    {//GEN-HEADEREND:event_jButNewStudentActionPerformed
        NewStudent newStudent = new NewStudent(this, true);
        newStudent.setVisible(true);
    }//GEN-LAST:event_jButNewStudentActionPerformed

    private void jButShowStudentsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButShowStudentsActionPerformed
    {//GEN-HEADEREND:event_jButShowStudentsActionPerformed
        ShowStudent showStudent = new ShowStudent(this, true);
        showStudent.setVisible(true);
    }//GEN-LAST:event_jButShowStudentsActionPerformed

    private void jButDeleteStudentsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButDeleteStudentsActionPerformed
    {//GEN-HEADEREND:event_jButDeleteStudentsActionPerformed
        DeleteStudent deleteStudent = new DeleteStudent(this, true);
        deleteStudent.setVisible(true);
    }//GEN-LAST:event_jButDeleteStudentsActionPerformed

    private void jButSearchStudentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButSearchStudentActionPerformed
    {//GEN-HEADEREND:event_jButSearchStudentActionPerformed
        SearchStudent searchStudent = new SearchStudent(this, true);
        searchStudent.setVisible(true);
    }//GEN-LAST:event_jButSearchStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButDeleteStudents;
    private javax.swing.JButton jButExit;
    private javax.swing.JButton jButNewStudent;
    private javax.swing.JButton jButSearchStudent;
    private javax.swing.JButton jButShowStudents;
    private javax.swing.JLabel jLabTitle;
    // End of variables declaration//GEN-END:variables
}
